/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistrationSubmittedRouteImport } from './routes/registration-submitted'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminAdmissionsRouteImport } from './routes/_authenticated/admin.admissions'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationSubmittedRoute = RegistrationSubmittedRouteImport.update({
  id: '/registration-submitted',
  path: '/registration-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/_authenticated/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAdmissionsRoute =
  AuthenticatedAdminAdmissionsRouteImport.update({
    id: '/_authenticated/admin/admissions',
    path: '/admin/admissions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/registration-submitted': typeof RegistrationSubmittedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/admissions': typeof AuthenticatedAdminAdmissionsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/registration-submitted': typeof RegistrationSubmittedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/admissions': typeof AuthenticatedAdminAdmissionsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/registration-submitted': typeof RegistrationSubmittedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/admin/admissions': typeof AuthenticatedAdminAdmissionsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/login'
    | '/register'
    | '/registration-submitted'
    | '/reset-password'
    | '/dashboard'
    | '/admin/login'
    | '/admin/admissions'
    | '/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/login'
    | '/register'
    | '/registration-submitted'
    | '/reset-password'
    | '/dashboard'
    | '/admin/login'
    | '/admin/admissions'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/login'
    | '/register'
    | '/registration-submitted'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/admin/login'
    | '/_authenticated/admin/admissions'
    | '/_authenticated/admin/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RegistrationSubmittedRoute: typeof RegistrationSubmittedRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthenticatedAdminAdmissionsRoute: typeof AuthenticatedAdminAdmissionsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-submitted': {
      id: '/registration-submitted'
      path: '/registration-submitted'
      fullPath: '/registration-submitted'
      preLoaderRoute: typeof RegistrationSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/admissions': {
      id: '/_authenticated/admin/admissions'
      path: '/admin/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AuthenticatedAdminAdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RegistrationSubmittedRoute: RegistrationSubmittedRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthenticatedAdminAdmissionsRoute: AuthenticatedAdminAdmissionsRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
